import React, { useEffect, useRef, useState } from 'react'
import { Eye, EyeOff, Plus, Trash2 } from 'lucide-react'
import { ENGINE_DEFAULTS, type AuthConfig, type TestDefinition, type EngineType } from '@shared/types'
import NumberInput from './NumberInput'

export interface RequestEditorProps {
  url: string
  onUrlChange: (url: string) => void
  headers: Record<string, string>
  onHeadersChange: (headers: Record<string, string>) => void
  body: string
  onBodyChange: (body: string) => void
  auth?: AuthConfig
  onAuthChange: (auth: AuthConfig) => void
  load?: TestDefinition['load']
  onLoadChange?: (load: Partial<TestDefinition['load']>) => void
  engine?: EngineType
  onEngineChange?: (engine: EngineType) => void
}

type TabType = 'params' | 'auth' | 'headers' | 'body' | 'load' | 'engine'

interface ParamRow {
  id: string
  enabled: boolean
  key: string
  value: string
}

interface HeaderRow {
  id: string
  enabled: boolean
  key: string
  value: string
}

let rowIdCounter = 1
const genId = (prefix: string): string => `${prefix}-${rowIdCounter++}-${Date.now().toString(36)}`

export default function RequestEditor({
  url,
  onUrlChange,
  headers,
  onHeadersChange,
  body,
  onBodyChange,
  auth = { type: 'none' },
  onAuthChange,
  load,
  onLoadChange,
  engine = 'autocannon',
  onEngineChange
}: RequestEditorProps): JSX.Element {
  const [activeTab, setActiveTab] = useState<TabType>('params')

  // ----------------------------------------------------
  // PARAMS (Dynamic 2-way sync with URL)
  // ----------------------------------------------------
  const [params, setParams] = useState<ParamRow[]>(() => parseParamsFromUrl(url))
  const lastGeneratedQueryRef = useRef<string | null>(null)

  // Sync params when URL changes from outside (e.g. typing in URL bar)
  useEffect(() => {
    const qIndex = url.indexOf('?')
    const currentQuery = qIndex !== -1 ? url.slice(qIndex + 1).split('#')[0] : ''

    // If this URL change was generated by our own params table, skip re-parsing
    if (currentQuery === lastGeneratedQueryRef.current) {
      return
    }

    const parsed = parseParamsFromUrl(url)
    // Preserve any disabled rows from existing params that might not be in the URL
    setParams((prev) => {
      const disabledRows = prev.filter((p) => !p.enabled && p.key.trim() !== '')
      return [...parsed, ...disabledRows]
    })
  }, [url])

  // Update URL whenever params change from table interaction
  const commitParamsToUrl = (nextParams: ParamRow[]): void => {
    setParams(nextParams)
    const active = nextParams.filter((p) => p.enabled && p.key.trim() !== '')
    const sp = new URLSearchParams()
    for (const p of active) {
      sp.append(p.key.trim(), p.value)
    }
    const newQuery = sp.toString()
    lastGeneratedQueryRef.current = newQuery

    const qIndex = url.indexOf('?')
    const hashIndex = url.indexOf('#')
    const base =
      qIndex !== -1 ? url.slice(0, qIndex) : hashIndex !== -1 ? url.slice(0, hashIndex) : url
    const hash = hashIndex !== -1 ? url.slice(hashIndex) : ''

    const nextUrl = newQuery ? `${base}?${newQuery}${hash}` : `${base}${hash}`
    onUrlChange(nextUrl)
  }

  const handleParamToggle = (id: string): void => {
    const next = params.map((p) => (p.id === id ? { ...p, enabled: !p.enabled } : p))
    commitParamsToUrl(next)
  }

  const handleParamChange = (id: string, field: 'key' | 'value', val: string): void => {
    const next = params.map((p) => (p.id === id ? { ...p, [field]: val } : p))
    commitParamsToUrl(next)
  }

  const handleParamDelete = (id: string): void => {
    const next = params.filter((p) => p.id !== id)
    commitParamsToUrl(next)
  }

  const handleNewParamChange = (field: 'key' | 'value', val: string): void => {
    if (!val.trim() && field === 'key') return
    const newRow: ParamRow = {
      id: genId('param'),
      enabled: true,
      key: field === 'key' ? val : '',
      value: field === 'value' ? val : ''
    }
    commitParamsToUrl([...params, newRow])
  }

  // ----------------------------------------------------
  // HEADERS (Table with enabled checkboxes)
  // ----------------------------------------------------
  const [headerRows, setHeaderRows] = useState<HeaderRow[]>(() => {
    return Object.entries(headers).map(([k, v]) => ({
      id: genId('hdr'),
      enabled: true,
      key: k,
      value: v
    }))
  })

  // Sync header rows when external headers prop changes (if keys changed)
  useEffect(() => {
    setHeaderRows((prev) => {
      const activeMap = Object.fromEntries(
        prev.filter((r) => r.enabled && r.key.trim()).map((r) => [r.key.trim(), r.value])
      )
      const isSame =
        Object.keys(activeMap).length === Object.keys(headers).length &&
        Object.entries(headers).every(([k, v]) => activeMap[k] === v)
      if (isSame) return prev

      const nextRows: HeaderRow[] = Object.entries(headers).map(([k, v]) => ({
        id: genId('hdr'),
        enabled: true,
        key: k,
        value: v
      }))
      // Keep any disabled rows
      const disabled = prev.filter((r) => !r.enabled && r.key.trim())
      return [...nextRows, ...disabled]
    })
  }, [headers])

  const commitHeaderRows = (nextRows: HeaderRow[]): void => {
    setHeaderRows(nextRows)
    const nextHeaders: Record<string, string> = {}
    for (const r of nextRows) {
      if (r.enabled && r.key.trim() !== '') {
        nextHeaders[r.key.trim()] = r.value
      }
    }
    onHeadersChange(nextHeaders)
  }

  const handleHeaderToggle = (id: string): void => {
    const next = headerRows.map((r) => (r.id === id ? { ...r, enabled: !r.enabled } : r))
    commitHeaderRows(next)
  }

  const handleHeaderChange = (id: string, field: 'key' | 'value', val: string): void => {
    const next = headerRows.map((r) => (r.id === id ? { ...r, [field]: val } : r))
    commitHeaderRows(next)
  }

  const handleHeaderDelete = (id: string): void => {
    const next = headerRows.filter((r) => r.id !== id)
    commitHeaderRows(next)
  }

  const handleNewHeaderChange = (field: 'key' | 'value', val: string): void => {
    if (!val.trim() && field === 'key') return
    const newRow: HeaderRow = {
      id: genId('hdr'),
      enabled: true,
      key: field === 'key' ? val : '',
      value: field === 'value' ? val : ''
    }
    commitHeaderRows([...headerRows, newRow])
  }

  const handleAddCookie = (): void => {
    const exists = headerRows.some((r) => r.key.toLowerCase() === 'cookie')
    if (exists) return
    const newRow: HeaderRow = {
      id: genId('hdr'),
      enabled: true,
      key: 'Cookie',
      value: ''
    }
    commitHeaderRows([...headerRows, newRow])
  }

  // ----------------------------------------------------
  // AUTH (Bearer, Basic, API Key)
  // ----------------------------------------------------
  const [showPassword, setShowPassword] = useState(false)

  const handleAuthTypeChange = (type: AuthConfig['type']): void => {
    const nextAuth: AuthConfig = { ...auth, type }
    onAuthChange(nextAuth)
    syncAuthToRequest(nextAuth)
  }

  const handleAuthFieldChange = (field: keyof AuthConfig, val: string): void => {
    const nextAuth = { ...auth, [field]: val }
    onAuthChange(nextAuth)
    syncAuthToRequest(nextAuth)
  }

  const syncAuthToRequest = (targetAuth: AuthConfig): void => {
    const nextH = { ...headers }

    if (targetAuth.type === 'bearer') {
      if (targetAuth.token?.trim()) {
        nextH['Authorization'] = `Bearer ${targetAuth.token.trim()}`
      } else {
        delete nextH['Authorization']
      }
      onHeadersChange(nextH)
    } else if (targetAuth.type === 'basic') {
      const u = targetAuth.username || ''
      const p = targetAuth.password || ''
      if (u || p) {
        try {
          const encoded = btoa(`${u}:${p}`)
          nextH['Authorization'] = `Basic ${encoded}`
        } catch {
          // Ignore btoa encoding issues
        }
      } else {
        delete nextH['Authorization']
      }
      onHeadersChange(nextH)
    } else if (targetAuth.type === 'apikey') {
      const keyName = targetAuth.key?.trim()
      const val = targetAuth.value ?? ''
      if (targetAuth.addTo === 'query') {
        delete nextH[keyName || '']
        onHeadersChange(nextH)
        // Add to query params if key exists
        if (keyName) {
          const existingIdx = params.findIndex((p) => p.key === keyName)
          let nextP: ParamRow[]
          if (existingIdx !== -1) {
            nextP = params.map((p, idx) => (idx === existingIdx ? { ...p, value: val } : p))
          } else {
            nextP = [...params, { id: genId('param'), enabled: true, key: keyName, value: val }]
          }
          commitParamsToUrl(nextP)
        }
      } else {
        // Add to header
        if (keyName) {
          nextH[keyName] = val
        }
        onHeadersChange(nextH)
      }
    } else {
      // 'none'
      if (headers['Authorization']?.startsWith('Bearer ') || headers['Authorization']?.startsWith('Basic ')) {
        delete nextH['Authorization']
        onHeadersChange(nextH)
      }
    }
  }

  // ----------------------------------------------------
  // BODY (none, raw JSON / text)
  // ----------------------------------------------------
  const [bodyMode, setBodyMode] = useState<'none' | 'raw'>(() => (body ? 'raw' : 'none'))
  const [rawFormat, setRawFormat] = useState<'json' | 'text' | 'xml' | 'html'>('json')

  const handleBodyModeChange = (mode: 'none' | 'raw'): void => {
    setBodyMode(mode)
    if (mode === 'none') {
      onBodyChange('')
    } else {
      // Default sample body if currently empty
      if (!body) {
        onBodyChange('{\n  \n}')
      }
      // Ensure Content-Type is set
      if (!headers['Content-Type']) {
        onHeadersChange({ ...headers, 'Content-Type': 'application/json' })
      }
    }
  }

  const handleFormatChange = (fmt: 'json' | 'text' | 'xml' | 'html'): void => {
    setRawFormat(fmt)
    const ctMap: Record<string, string> = {
      json: 'application/json',
      text: 'text/plain',
      xml: 'application/xml',
      html: 'text/html'
    }
    onHeadersChange({ ...headers, 'Content-Type': ctMap[fmt] })
  }

  const handleBeautifyJson = (): void => {
    try {
      const parsed = JSON.parse(body)
      onBodyChange(JSON.stringify(parsed, null, 2))
    } catch {
      alert('Cannot format: Request body contains invalid JSON.')
    }
  }

  const activeParamsCount = params.filter((p) => p.enabled && p.key.trim() !== '').length
  const activeHeadersCount = headerRows.filter((r) => r.enabled && r.key.trim() !== '').length
  const isAuthActive = auth.type !== 'none'
  const isBodyActive = bodyMode === 'raw' && body.trim().length > 0

  return (
    <div className="card postman-card">
      {/* Sub-tabs bar */}
      <div className="postman-tabs-bar">
        <button
          type="button"
          className={`postman-tab-btn ${activeTab === 'params' ? 'active' : ''}`}
          onClick={() => setActiveTab('params')}
        >
          Params
          {activeParamsCount > 0 && <span className="postman-tab-badge">{activeParamsCount}</span>}
        </button>
        <button
          type="button"
          className={`postman-tab-btn ${activeTab === 'auth' ? 'active' : ''}`}
          onClick={() => setActiveTab('auth')}
        >
          Auth
          {isAuthActive && <span className="postman-tab-dot" />}
        </button>
        <button
          type="button"
          className={`postman-tab-btn ${activeTab === 'headers' ? 'active' : ''}`}
          onClick={() => setActiveTab('headers')}
        >
          Headers
          {activeHeadersCount > 0 && <span className="postman-tab-badge">{activeHeadersCount}</span>}
        </button>
        <button
          type="button"
          className={`postman-tab-btn ${activeTab === 'body' ? 'active' : ''}`}
          onClick={() => setActiveTab('body')}
        >
          Body
          {isBodyActive && <span className="postman-tab-dot" />}
        </button>
        {load && (
          <button
            type="button"
            className={`postman-tab-btn ${activeTab === 'load' ? 'active' : ''}`}
            onClick={() => setActiveTab('load')}
          >
            Load
            <span className="postman-tab-badge">{load.connections}c / {load.durationSeconds}s</span>
          </button>
        )}
        {engine && (
          <button
            type="button"
            className={`postman-tab-btn ${activeTab === 'engine' ? 'active' : ''}`}
            onClick={() => setActiveTab('engine')}
          >
            Engine
            <span className="postman-tab-badge" style={{ textTransform: 'capitalize' }}>{engine}</span>
          </button>
        )}
      </div>

      {/* Tab Panels */}
      <div className="postman-tab-panel">
        {/* PARAMS TAB */}
        {activeTab === 'params' && (
          <div>
            <div className="tab-section-header">
              <span className="tab-section-title">Query Parameters</span>
            </div>
            <table className="kv-table">
              <thead>
                <tr>
                  <th style={{ width: 34, textAlign: 'center' }}></th>
                  <th style={{ width: '45%' }}>Key</th>
                  <th>Value</th>
                  <th style={{ width: 34, textAlign: 'center' }}></th>
                </tr>
              </thead>
              <tbody>
                {params.map((p) => (
                  <tr key={p.id}>
                    <td style={{ textAlign: 'center' }}>
                      <input
                        type="checkbox"
                        checked={p.enabled}
                        onChange={() => handleParamToggle(p.id)}
                        title={p.enabled ? 'Disable parameter' : 'Enable parameter'}
                      />
                    </td>
                    <td>
                      <input
                        type="text"
                        value={p.key}
                        placeholder="Key"
                        style={{ opacity: p.enabled ? 1 : 0.5 }}
                        onChange={(e) => handleParamChange(p.id, 'key', e.target.value)}
                      />
                    </td>
                    <td>
                      <input
                        type="text"
                        value={p.value}
                        placeholder="Value"
                        style={{ opacity: p.enabled ? 1 : 0.5 }}
                        onChange={(e) => handleParamChange(p.id, 'value', e.target.value)}
                      />
                    </td>
                    <td style={{ textAlign: 'center' }}>
                      <button
                        type="button"
                        className="kv-del-btn"
                        onClick={() => handleParamDelete(p.id)}
                        title="Delete parameter"
                      >
                        <Trash2 size={12} />
                      </button>
                    </td>
                  </tr>
                ))}
                {/* Empty input row for quick entry */}
                <tr className="kv-empty-row">
                  <td style={{ textAlign: 'center', opacity: 0.35 }}>
                    <input type="checkbox" disabled />
                  </td>
                  <td>
                    <input
                      type="text"
                      placeholder="Key"
                      onChange={(e) => {
                        handleNewParamChange('key', e.target.value)
                        e.target.value = ''
                      }}
                    />
                  </td>
                  <td>
                    <input
                      type="text"
                      placeholder="Value"
                      onChange={(e) => {
                        handleNewParamChange('value', e.target.value)
                        e.target.value = ''
                      }}
                    />
                  </td>
                  <td></td>
                </tr>
              </tbody>
            </table>
          </div>
        )}

        {/* AUTH TAB */}
        {activeTab === 'auth' && (
          <div className="auth-panel">
            <div className="row" style={{ alignItems: 'center', marginBottom: 14 }}>
              <label className="field" style={{ width: 220, flex: 'none' }}>
                Auth Type
                <select
                  value={auth.type}
                  onChange={(e) => handleAuthTypeChange(e.target.value as AuthConfig['type'])}
                >
                  <option value="none">No Auth</option>
                  <option value="bearer">Bearer Token</option>
                  <option value="basic">Basic Auth</option>
                  <option value="apikey">API Key</option>
                </select>
              </label>
            </div>

            {auth.type === 'bearer' && (
              <div className="auth-fields">
                <label className="field">
                  Token
                  <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                    <input
                      type={showPassword ? 'text' : 'password'}
                      value={auth.token ?? ''}
                      placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      style={{ paddingRight: 32 }}
                      onChange={(e) => handleAuthFieldChange('token', e.target.value)}
                    />
                    <button
                      type="button"
                      tabIndex={-1}
                      className="kv-eye-btn"
                      onClick={() => setShowPassword((s) => !s)}
                      title={showPassword ? 'Hide token' : 'Show token'}
                    >
                      {showPassword ? <EyeOff size={13} /> : <Eye size={13} />}
                    </button>
                  </div>
                </label>
                {auth.token && (
                  <div className="auth-preview-badge">
                    Header: <code>Authorization: Bearer {auth.token.slice(0, 16)}…</code>
                  </div>
                )}
              </div>
            )}

            {auth.type === 'basic' && (
              <div className="auth-fields">
                <div className="row">
                  <label className="field">
                    Username
                    <input
                      type="text"
                      value={auth.username ?? ''}
                      placeholder="admin"
                      onChange={(e) => handleAuthFieldChange('username', e.target.value)}
                    />
                  </label>
                  <label className="field">
                    Password
                    <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                      <input
                        type={showPassword ? 'text' : 'password'}
                        value={auth.password ?? ''}
                        placeholder="••••••••"
                        style={{ paddingRight: 32 }}
                        onChange={(e) => handleAuthFieldChange('password', e.target.value)}
                      />
                      <button
                        type="button"
                        tabIndex={-1}
                        className="kv-eye-btn"
                        onClick={() => setShowPassword((s) => !s)}
                        title={showPassword ? 'Hide password' : 'Show password'}
                      >
                        {showPassword ? <EyeOff size={13} /> : <Eye size={13} />}
                      </button>
                    </div>
                  </label>
                </div>
                {(auth.username || auth.password) && (
                  <div className="auth-preview-badge">
                    Header: <code>Authorization: Basic [base64-encoded]</code>
                  </div>
                )}
              </div>
            )}

            {auth.type === 'apikey' && (
              <div className="auth-fields">
                <div className="row">
                  <label className="field">
                    Key Name
                    <input
                      type="text"
                      value={auth.key ?? ''}
                      placeholder="X-API-Key"
                      onChange={(e) => handleAuthFieldChange('key', e.target.value)}
                    />
                  </label>
                  <label className="field">
                    Value
                    <input
                      type="text"
                      value={auth.value ?? ''}
                      placeholder="api-key-value"
                      onChange={(e) => handleAuthFieldChange('value', e.target.value)}
                    />
                  </label>
                  <label className="field" style={{ maxWidth: 160 }}>
                    Add to
                    <select
                      value={auth.addTo ?? 'header'}
                      onChange={(e) => handleAuthFieldChange('addTo', e.target.value)}
                    >
                      <option value="header">Header</option>
                      <option value="query">Query Params</option>
                    </select>
                  </label>
                </div>
              </div>
            )}
          </div>
        )}

        {/* HEADERS TAB */}
        {activeTab === 'headers' && (
          <div>
            <div className="tab-section-header">
              <span className="tab-section-title">Headers</span>
              <div style={{ display: 'flex', gap: 6 }}>
                <button
                  type="button"
                  style={{ fontSize: 11, padding: '2px 8px' }}
                  onClick={handleAddCookie}
                  disabled={headerRows.some((r) => r.key.toLowerCase() === 'cookie')}
                >
                  + Add Cookie
                </button>
              </div>
            </div>
            <table className="kv-table">
              <thead>
                <tr>
                  <th style={{ width: 34, textAlign: 'center' }}></th>
                  <th style={{ width: '45%' }}>Key</th>
                  <th>Value</th>
                  <th style={{ width: 34, textAlign: 'center' }}></th>
                </tr>
              </thead>
              <tbody>
                {headerRows.map((r) => (
                  <tr key={r.id}>
                    <td style={{ textAlign: 'center' }}>
                      <input
                        type="checkbox"
                        checked={r.enabled}
                        onChange={() => handleHeaderToggle(r.id)}
                        title={r.enabled ? 'Disable header' : 'Enable header'}
                      />
                    </td>
                    <td>
                      <input
                        type="text"
                        value={r.key}
                        placeholder="Header"
                        style={{ opacity: r.enabled ? 1 : 0.5 }}
                        onChange={(e) => handleHeaderChange(r.id, 'key', e.target.value)}
                      />
                    </td>
                    <td>
                      <input
                        type="text"
                        value={r.value}
                        placeholder="Value"
                        style={{ opacity: r.enabled ? 1 : 0.5 }}
                        onChange={(e) => handleHeaderChange(r.id, 'value', e.target.value)}
                      />
                    </td>
                    <td style={{ textAlign: 'center' }}>
                      <button
                        type="button"
                        className="kv-del-btn"
                        onClick={() => handleHeaderDelete(r.id)}
                        title="Delete header"
                      >
                        <Trash2 size={12} />
                      </button>
                    </td>
                  </tr>
                ))}
                {/* Empty input row for quick entry */}
                <tr className="kv-empty-row">
                  <td style={{ textAlign: 'center', opacity: 0.35 }}>
                    <input type="checkbox" disabled />
                  </td>
                  <td>
                    <input
                      type="text"
                      placeholder="Key"
                      onChange={(e) => {
                        handleNewHeaderChange('key', e.target.value)
                        e.target.value = ''
                      }}
                    />
                  </td>
                  <td>
                    <input
                      type="text"
                      placeholder="Value"
                      onChange={(e) => {
                        handleNewHeaderChange('value', e.target.value)
                        e.target.value = ''
                      }}
                    />
                  </td>
                  <td></td>
                </tr>
              </tbody>
            </table>
            {headerRows.some((r) => r.key.toLowerCase() === 'cookie') && (
              <p style={{ fontSize: 11, color: 'var(--muted)', marginTop: 6, marginBottom: 0 }}>
                Cookie format: <code>name=value; session_id=xyz123</code>
              </p>
            )}
          </div>
        )}

        {/* BODY TAB */}
        {activeTab === 'body' && (
          <div>
            <div className="tab-section-header" style={{ marginBottom: 8 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <label style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 12, cursor: 'pointer' }}>
                  <input
                    type="radio"
                    name="bodyMode"
                    checked={bodyMode === 'none'}
                    onChange={() => handleBodyModeChange('none')}
                  />
                  none
                </label>
                <label style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 12, cursor: 'pointer' }}>
                  <input
                    type="radio"
                    name="bodyMode"
                    checked={bodyMode === 'raw'}
                    onChange={() => handleBodyModeChange('raw')}
                  />
                  raw
                </label>
              </div>

              {bodyMode === 'raw' && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <select
                    value={rawFormat}
                    onChange={(e) => handleFormatChange(e.target.value as 'json' | 'text' | 'xml' | 'html')}
                    style={{ width: 85, fontSize: 11, padding: '2px 6px' }}
                  >
                    <option value="json">JSON</option>
                    <option value="text">Text</option>
                    <option value="xml">XML</option>
                    <option value="html">HTML</option>
                  </select>
                  {rawFormat === 'json' && (
                    <button
                      type="button"
                      style={{ fontSize: 11, padding: '2px 8px' }}
                      onClick={handleBeautifyJson}
                      title="Format JSON payload with indentation"
                    >
                      Beautify
                    </button>
                  )}
                  {body && (
                    <button
                      type="button"
                      style={{ fontSize: 11, padding: '2px 8px' }}
                      onClick={() => onBodyChange('')}
                      title="Clear payload"
                    >
                      Clear
                    </button>
                  )}
                </div>
              )}
            </div>

            {bodyMode === 'none' ? (
              <div className="empty" style={{ padding: '24px 12px' }}>
                This request does not have a body payload.
                <div style={{ marginTop: 8 }}>
                  <button
                    type="button"
                    style={{ fontSize: 11 }}
                    onClick={() => handleBodyModeChange('raw')}
                  >
                    <Plus size={11} style={{ marginRight: 4, verticalAlign: 'middle' }} />
                    Add Raw Body
                  </button>
                </div>
              </div>
            ) : (
              <textarea
                className="code-textarea"
                rows={8}
                value={body}
                placeholder={rawFormat === 'json' ? '{\n  "key": "value"\n}' : 'Request body payload...'}
                onChange={(e) => onBodyChange(e.target.value)}
                onKeyDown={(e) => {
                  // Support indentation on Tab press
                  if (e.key === 'Tab') {
                    e.preventDefault()
                    const start = e.currentTarget.selectionStart
                    const end = e.currentTarget.selectionEnd
                    const nextVal = body.substring(0, start) + '  ' + body.substring(end)
                    onBodyChange(nextVal)
                    setTimeout(() => {
                      if (e.currentTarget) {
                        e.currentTarget.selectionStart = e.currentTarget.selectionEnd = start + 2
                      }
                    }, 0)
                  }
                }}
                spellCheck={false}
              />
            )}
          </div>
        )}

        {/* LOAD TAB */}
        {activeTab === 'load' && load && onLoadChange && (
          <div>
            <div className="tab-section-header">
              <span className="tab-section-title">Load Configuration</span>
              <button
                type="button"
                style={{ fontSize: 11, padding: '2px 8px', color: 'var(--muted)' }}
                title="Reset load settings to current engine defaults"
                onClick={() => onLoadChange({ ...ENGINE_DEFAULTS[engine] })}
              >
                Reset to defaults
              </button>
            </div>
            <div className="row" style={{ marginTop: 8 }}>
              <label className="field">
                Connections
                <NumberInput
                  min={1}
                  value={load.connections}
                  placeholder={String(ENGINE_DEFAULTS[engine]?.connections ?? 100)}
                  onChange={(val) => onLoadChange({ connections: val as number })}
                />
              </label>
              <label className="field">
                Duration (seconds)
                <NumberInput
                  min={1}
                  value={load.durationSeconds}
                  placeholder={String(ENGINE_DEFAULTS[engine]?.durationSeconds ?? 30)}
                  onChange={(val) => onLoadChange({ durationSeconds: val as number })}
                />
              </label>
              <label className="field">
                Pipelining
                <NumberInput
                  min={1}
                  value={load.pipelining}
                  placeholder={String(ENGINE_DEFAULTS[engine]?.pipelining ?? 1)}
                  onChange={(val) => onLoadChange({ pipelining: val as number })}
                />
              </label>
              <label className="field">
                Rate cap (req/s, optional)
                <NumberInput
                  min={1}
                  value={load.rate}
                  placeholder="unlimited"
                  onChange={(val) => onLoadChange({ rate: val })}
                />
              </label>
            </div>
          </div>
        )}

        {/* ENGINE TAB */}
        {activeTab === 'engine' && onEngineChange && (
          <div>
            <div className="tab-section-header">
              <span className="tab-section-title">Load Testing Engine</span>
            </div>
            <div style={{ maxWidth: 360, marginTop: 8 }}>
              <label className="field">
                Engine
                <select
                  value={engine}
                  onChange={(e) => onEngineChange(e.target.value as EngineType)}
                >
                  <option value="autocannon">Autocannon (Default)</option>
                  <option value="loadtest">loadtest (ab-compatible)</option>
                  <option value="artillery">Artillery (Scenario Runner)</option>
                </select>
              </label>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function parseParamsFromUrl(fullUrl: string): ParamRow[] {
  try {
    const qIndex = fullUrl.indexOf('?')
    if (qIndex === -1) return []
    const qs = fullUrl.slice(qIndex + 1).split('#')[0]
    if (!qs.trim()) return []

    const searchParams = new URLSearchParams(qs)
    const items: ParamRow[] = []
    for (const [key, value] of searchParams.entries()) {
      items.push({
        id: genId('param'),
        enabled: true,
        key,
        value
      })
    }
    return items
  } catch {
    return []
  }
}
